permissions:
  checks: write
  contents: write
  packages: read
name: pushes

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_dev }}
          debug: "true"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"

  gather_analytics:
    name: Gather Analytics
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_dev }}
          send_job_status: "true"
          debug: "true"
